export default [
  {
    code: 'MNL-BEVCLDLRG',
    name: 'Cafe Mocha',
    description: '',
    categoryCode: 'BEV',
    variations: {},
    price: 10,
    branchCode: 'MNL',
    createdBy: 'jeff',
    createdDate: '2019-03-05 00:00',
  },
  {
    code: 'MNL-BEVHTLRG',
    name: 'Caffe Americano',
    description: '',
    categoryCode: 'BEV',
    variations: {},
    price: 10,
    branchCode: 'MNL',
    createdBy: 'jeff',
    createdDate: '2019-03-05 00:00',
  },
  {
    code: 'MNL-BEVHTLRG',
    name: 'Cafe Latte',
    description: '',
    categoryCode: 'BEV',
    variations: {},
    price: 10,
    branchCode: 'MNL',
    createdBy: 'jeff',
    createdDate: '2019-03-05 00:00',
  },
  {
    code: 'MNL-BEVHTLRG',
    name: 'Caramel Machiatto',
    description: '',
    categoryCode: 'BEV',
    variations: {},
    price: 10,
    branchCode: 'MNL',
    createdBy: 'jeff',
    createdDate: '2019-03-05 00:00',
  },
];
